
/*
# Incident Raise System – Core Schema

## Overview
Creates the complete schema for the Incident/Ticket Management System.
This supports role-based access (employee vs. admin) with full RLS enforcement.

## New Tables

### 1. `profiles`
Extends Supabase auth.users with:
- `id` (uuid, PK, FK → auth.users)
- `name` (text) — display name
- `role` (text) — 'user' or 'admin'
- `created_at`, `updated_at` timestamps

### 2. `tickets`
Core incident/ticket table:
- `id` (uuid, PK)
- `ticket_number` (text, unique) — human-readable ID like INC-00001
- `title` (text)
- `description` (text)
- `category` (text) — Hardware, Software, Network, etc.
- `priority` (text) — Low, Medium, High, Critical
- `status` (text) — Open, In Progress, Resolved, Closed
- `created_by` (uuid, FK → auth.users)
- `assigned_to` (uuid, nullable FK → auth.users)
- `created_at`, `updated_at` timestamps

### 3. `ticket_history`
Audit log for every status/priority change on a ticket:
- `id` (uuid, PK)
- `ticket_id` (uuid, FK → tickets)
- `changed_by` (uuid, FK → auth.users)
- `field` (text) — 'status' or 'priority'
- `old_value` (text)
- `new_value` (text)
- `created_at` timestamp

## Security
- RLS enabled on all tables.
- Profiles: users can read any profile (for admin name display), update only their own.
- Tickets: employees see only their own; admins see all via a separate policy.
- Ticket history: same scoping as tickets.

## Important Notes
1. Admin detection uses a function `is_admin()` that reads the profiles table.
2. The `ticket_number` is auto-generated by a trigger using a sequence.
3. `updated_at` is auto-maintained by a trigger.
*/

-- ============================================================
-- PROFILES TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT '',
  role text NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select" ON profiles;
CREATE POLICY "profiles_select" ON profiles FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "profiles_insert" ON profiles;
CREATE POLICY "profiles_insert" ON profiles FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update" ON profiles;
CREATE POLICY "profiles_update" ON profiles FOR UPDATE
  TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_delete" ON profiles;
CREATE POLICY "profiles_delete" ON profiles FOR DELETE
  TO authenticated USING (false);

-- ============================================================
-- HELPER: is_admin()
-- ============================================================
CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
  );
$$;

-- ============================================================
-- TICKET NUMBER SEQUENCE & GENERATOR
-- ============================================================
CREATE SEQUENCE IF NOT EXISTS ticket_number_seq START 1;

CREATE OR REPLACE FUNCTION generate_ticket_number()
RETURNS text
LANGUAGE sql
AS $$
  SELECT 'INC-' || LPAD(nextval('ticket_number_seq')::text, 5, '0');
$$;

-- ============================================================
-- TICKETS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS tickets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_number text UNIQUE NOT NULL DEFAULT generate_ticket_number(),
  title text NOT NULL,
  description text NOT NULL,
  category text NOT NULL CHECK (category IN (
    'Hardware','Software','Network','Email','Printer',
    'Access','Security','Database','Server','Other'
  )),
  priority text NOT NULL DEFAULT 'Medium' CHECK (priority IN ('Low','Medium','High','Critical')),
  status text NOT NULL DEFAULT 'Open' CHECK (status IN ('Open','In Progress','Resolved','Closed')),
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  assigned_to uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS tickets_created_by_idx ON tickets(created_by);
CREATE INDEX IF NOT EXISTS tickets_status_idx ON tickets(status);
CREATE INDEX IF NOT EXISTS tickets_priority_idx ON tickets(priority);
CREATE INDEX IF NOT EXISTS tickets_created_at_idx ON tickets(created_at DESC);

ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;

-- Employees see their own; admins see all
DROP POLICY IF EXISTS "tickets_select" ON tickets;
CREATE POLICY "tickets_select" ON tickets FOR SELECT
  TO authenticated
  USING (auth.uid() = created_by OR is_admin());

DROP POLICY IF EXISTS "tickets_insert" ON tickets;
CREATE POLICY "tickets_insert" ON tickets FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = created_by);

-- Only admins can update tickets
DROP POLICY IF EXISTS "tickets_update" ON tickets;
CREATE POLICY "tickets_update" ON tickets FOR UPDATE
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

-- Only admins can delete tickets
DROP POLICY IF EXISTS "tickets_delete" ON tickets;
CREATE POLICY "tickets_delete" ON tickets FOR DELETE
  TO authenticated
  USING (is_admin());

-- ============================================================
-- AUTO-UPDATE updated_at TRIGGER
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tickets_updated_at ON tickets;
CREATE TRIGGER tickets_updated_at
  BEFORE UPDATE ON tickets
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS profiles_updated_at ON profiles;
CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- TICKET HISTORY TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS ticket_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  changed_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  field text NOT NULL,
  old_value text,
  new_value text NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ticket_history_ticket_id_idx ON ticket_history(ticket_id);

ALTER TABLE ticket_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ticket_history_select" ON ticket_history;
CREATE POLICY "ticket_history_select" ON ticket_history FOR SELECT
  TO authenticated
  USING (
    is_admin()
    OR EXISTS (
      SELECT 1 FROM tickets
      WHERE tickets.id = ticket_history.ticket_id
        AND tickets.created_by = auth.uid()
    )
  );

DROP POLICY IF EXISTS "ticket_history_insert" ON ticket_history;
CREATE POLICY "ticket_history_insert" ON ticket_history FOR INSERT
  TO authenticated
  WITH CHECK (is_admin());

DROP POLICY IF EXISTS "ticket_history_update" ON ticket_history;
CREATE POLICY "ticket_history_update" ON ticket_history FOR UPDATE
  TO authenticated
  USING (false);

DROP POLICY IF EXISTS "ticket_history_delete" ON ticket_history;
CREATE POLICY "ticket_history_delete" ON ticket_history FOR DELETE
  TO authenticated
  USING (false);

-- ============================================================
-- AUTO-CREATE PROFILE TRIGGER (on auth.users insert)
-- ============================================================
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO profiles (id, name, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'role', 'user')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();
